service: default
api_version: v1
runtime: custom
vm: true

health_check:
  enable_health_check: true
  check_interval_sec: 6
  timeout_sec: 2
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 30
